# Generated by Django 4.1.4 on 2023-03-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scoala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_scoala', models.CharField(max_length=33, unique=True)),
                ('nume_director', models.CharField(max_length=20)),
                ('adresa_scoala', models.CharField(max_length=50, unique=True)),
                ('judet', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Scoli',
            },
        ),
    ]
