# Generated by Django 4.1.4 on 2023-03-12 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_digital', '0002_scoala_oras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseScoala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_clasa', models.CharField(max_length=20)),
                ('diriginte', models.CharField(max_length=20)),
                ('promotia', models.IntegerField(max_length=4)),
                ('scoala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_digital.scoala')),
            ],
            options={
                'verbose_name_plural': 'Clase Scoala',
            },
        ),
    ]
