# Generated by Django 4.1.4 on 2023-03-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_digital', '0003_clasescoala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasescoala',
            name='nume_clasa',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clasescoala',
            name='promotia',
            field=models.IntegerField(),
        ),
    ]
