# Generated by Django 4.1.4 on 2023-03-12 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_digital', '0004_alter_clasescoala_nume_clasa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_profesor', models.CharField(max_length=30)),
                ('materie', models.CharField(max_length=20)),
                ('numar_telefon_profesor', models.IntegerField()),
                ('adresa_mail_profesor', models.EmailField(max_length=254)),
                ('profesor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog_digital.scoala')),
            ],
            options={
                'verbose_name_plural': 'Profesori',
            },
        ),
    ]
