# Generated by Django 4.1.4 on 2023-03-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_digital', '0005_profesori'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesori',
            old_name='profesor',
            new_name='scoala',
        ),
    ]
