# Generated by Django 4.1.4 on 2023-03-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_digital', '0006_rename_profesor_profesori_scoala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_elev', models.CharField(max_length=30)),
                ('numar_telefon_elev', models.IntegerField()),
                ('adresa_mail_elev', models.EmailField(max_length=254)),
                ('clasa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog_digital.clasescoala')),
                ('scoala', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog_digital.scoala')),
            ],
            options={
                'verbose_name_plural': 'Elevi',
            },
        ),
    ]
