# Generated by Django 4.1.4 on 2023-03-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_digital', '0007_elevi'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParinteElev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_parinte', models.CharField(max_length=30)),
                ('numar_telefon_parinte', models.IntegerField()),
                ('adresa_mail_parinte', models.EmailField(max_length=254)),
                ('copil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalog_digital.elevi')),
            ],
            options={
                'verbose_name_plural': 'Parinti',
            },
        ),
    ]
