# Generated by Django 4.1.4 on 2023-04-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_digital', '0008_parinteelev'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevi',
            name='nume_parinte',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='elevi',
            name='clasa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='elevi',
            name='scoala',
            field=models.TextField(),
        ),
    ]
