# Generated by Django 4.1.4 on 2023-04-21 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_digital', '0011_alter_elevi_numar_telefon_elev'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elevi',
            old_name='adresa_mail_elev',
            new_name='adresa_mail',
        ),
        migrations.RenameField(
            model_name='elevi',
            old_name='numar_telefon_elev',
            new_name='numar_telefon',
        ),
    ]
